name: Build and Publish Artifact

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: '3.x'

    - name: Run build script
      shell: pwsh
      run: |
        .\build.ps1

    - name: Publish artifact
      uses: actions/upload-artifact@v2
      with:
        name: artifact
        path: dist/bin/rest_api.exe
